### ISSUE TITLE
Dashboard scroll should freeze the test names and dates.

### ISSUE THREAD

**Issue by taylanbil** [GoogleCloudPlatform/ml-testing-accelerators#109]
As more and more tests are added, we'll be scrolling when looking to the dashboard, and the top of the screen looks like: https://screenshot.googleplex.com/TvKeW5ivhuh

**Comment by zcain117** [comment]
I don't understand. Freeze the names? Scrolling to the left or to the right?

Also - could you upload the screenshot rather than linking to a .googleplex URL?

**Comment by taylanbil** [comment]
I mean scrolling down and scrolling to the right.

scroll down in [this sheet[(https://docs.google.com/spreadsheets/d/11SGN3iOF8SnOJfvE5XhANXQ52qzTXOUN7FiuIAzAA8Y/edit#gid=0), the 1st row and column are frozen.

**Comment by zcain117** [comment]
I can't access that sheet but I think now I know what you're talking about.

As you scroll to the right, the list of test names from the left axis should float along with you so you can see which row you're on even when you're quite far to the right.

Similar for when you scroll down, the test dates should float down too.

Right now the hover tip is set up to show the date as you hover over a box which is a good workaround for the test dates floating down. Could add the test name to the hover as well as a workaround if we can't get the yaxis or xaxis labels to float while scrolling

**Comment by taylanbil** [comment]
ah hovering tip is useful, thanks. I think scrolling to the right is less critical, vertical scrolling is probably the one I'd care about.
