### ISSUE TITLE
PyTorch Pods tests are failing due to Instance Groups not stabilizing in time.

### ISSUE THREAD

**Issue by taylanbil** [GoogleCloudPlatform/ml-testing-accelerators#120]
This is a non-interesting failure mode, and these failures are mostly noise.

Happened twice this week. [Example](https://pantheon.corp.google.com/logs/viewer?project=xl-ml-test&dateRangeUnbound=backwardInTime&pli=1&rapt=AEjHL4NPW9K9h_s-_v-mZlmp5UsEKM8EYdYRIqfmBHuIyTXKiD2LggRimKrE1_gQsYD0B9dSXmJap1QuCJ23U4R7ybS94zIuSA&minLogLevel=0&expandAll=false&timestamp=2020-04-29T17:03:57.377000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3Dk8s_container%0Aresource.labels.project_id%3Dxl-ml-test%0Aresource.labels.location%3Deurope-west4-a%0Aresource.labels.cluster_name%3Dxl-ml-test-europe-west4%0Aresource.labels.namespace_name%3Dautomated%0Aresource.labels.pod_name:pt-nightly-mnist-conv-v2-32-1588168800&dateRangeEnd=2020-04-29T17:03:57.377Z&interval=PT1H&scrollTimestamp=2020-04-29T14:27:51.970148385Z).

Instead of counting stable instances in the IG and sleeping, I think it would be better to use `gcloud compute instance-groups managed wait-until-stable $IG --zone $ZONE`. WDYT?

**Comment by will-cromar** [comment]
I think these issues were coming up because we lacked CPU quota in our project, which @zcain117 has since fixed. I agree that the command you recommend is a better solution to wait for the instance group to come up, though.

**Comment by taylanbil** [comment]
This happened yesterday and the day before. When was the quota fix?

**Comment by will-cromar** [comment]
The quota change went through yesterday afternoon.

**Comment by taylanbil** [comment]
awesome, I'll close this issue and leave the implementation change up to you.
