### ISSUE TITLE
Metrics History time series progressing from right to left feels awkward.

### ISSUE THREAD

**Issue by taylanbil** [GoogleCloudPlatform/ml-testing-accelerators#143]
example: https://xl-ml-test.appspot.com/metrics?test_name=pt-nightly-resnet50-func-v3-8

The newest entry is on the left, oldest is to the right. It feels weird and counterintuitive to me. I feel it would be better if it went from left to right, WDYT?

**Comment by zcain117** [comment]
I chose right to left for 2 reasons:

1. It matches the pass/fail dashboard (which in turn matches the Testgrid look that everyone is used to)
2. I think a common use case is to look at the history when the latest run is out of bounds. If the latest run was all the way on the right, people would have to scroll to the right to find the latest data point

We can get more opinions - it's an easy change to make
