### ISSUE TITLE
Dashboard colors get stuck when a cell is clicked.

### ISSUE THREAD

**Issue by taylanbil** [GoogleCloudPlatform/ml-testing-accelerators#77]
When I click a cell and then close the popup, colors get stuck like this: https://screenshot.googleplex.com/KgG3vdkxuYz

I can click on an empty pixel and it comes back.

**Comment by zcain117** [comment]
That feature is meant to help someone remember which square they were checking if they e.g. follow the link to stackdriver in a new tab. Maybe unnecessary now that I have the modal?

Maybe the 'selected square' view could reset once the user closes the modal?

**Comment by taylanbil** [comment]
hmm, I see. It felt awkward to me, but I understand. Please close this if you decide to stick w/ the current way.
